all: libpathplot.a

ROOT=..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I/usr/local/graphviz/include

DEFINES = -DHAVE_CONFIG_H

OBJS = PolyBarriers.o Route.o Shortest.o

HFILES = PathPlot.h BezCoeffs.h ../common/*.h

libpathplot.a : $(OBJS)
	$(AR) cr libpathplot.a $(OBJS)
	$(RANLIB) libpathplot.a

$(OBJS) : $(HFILES)

install: libpathplot.a
	$(MKPATH) $(LIBDIR)
	$(INSTALL) libpathplot.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
