all: libincrface.a

include ../../Config.mk
include ../../makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I../../agraph \
	-I../../cdt

DEFINES = -DHAVE_CONFIG_H

OBJS = View.o createLayoutServer.o incrscan.o incrgram.o incrcmds.o incrout.o

HFILES = createLayoutServer.h View.h incrcmds.h incrout.h incrxep.h

libincrface.a : $(OBJS)
	$(AR) cr libincrface.a $(OBJS)
	$(RANLIB) libincrface.a

$(OBJS) : $(HFILES)

install: libincrface.a
#	$(MKPATH) $(LIBDIR)
#	$(INSTALL) libincrface.a $(LIBDIR)

incrscan.cpp: incrscan.lpp
	$(FLEX) incrscan.lpp
	$(SED) "s/yy/incr_yy/g" < lex.yy.c > incrscan.cpp
	rm lex.yy.c

incrscan.o : incrgram.h
incrgram.h : incrgram.cpp

incrgram.cpp : incrgram.ypp
	$(BISON) -dv -o incrgram.tab.c incrgram.ypp
	$(SED) "s/yy/incr_yy/g" < incrgram.tab.c > incrgram.cpp
	$(SED) "s/yy/incr_yy/g" < incrgram.tab.h > incrgram.h
	rm incrgram.tab.c incrgram.tab.h

clean:
	$(RM) *.o core incrscan.cpp incrgram.cpp incrgram.h

distclean: clean
	$(RM) *.a lib*.so.*
