all: libincrface.a

ROOT=..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I/usr/local/graphviz/include

DEFINES = -DHAVE_CONFIG_H

OBJS = \
	DinoMachineTranslator.o	incrcmds.o		incrgram.o		incrscan.o

HFILES = \
	DinoMachine.h           DinoMachineTranslator.h DinoPatternLook.h       DinoSearchLook.h \
	IncrLangEvents.h        IncrStrGraphHandler.h   IncrViewWatcher.h \
	LabelToNameTranslator.h MatchNames.h \
	createStringHandlers.h \
	incrcmds.h              incrgram.h		incrout.h               incrparse.h \
	incrxep.h		two_way_map.h \
	../common/*.h		../fdp/*.h		../dynadag/*.h 		../voronoi/*.h \
	../pathplot/*.h		../shortspline/*.h
	

libincrface.a : $(OBJS)
	$(AR) cr libincrface.a $(OBJS)
	$(RANLIB) libincrface.a

$(OBJS) : $(HFILES)

install: libincrface.a
#	$(MKPATH) $(LIBDIR)
#	$(INSTALL) libincrface.a $(LIBDIR)

incrscan.cpp: incrscan.lpp
	$(FLEX) incrscan.lpp
	$(SED) "s/yy/incr_yy/g" < lex.yy.c > incrscan.cpp
	rm lex.yy.c

incrscan.o : incrgram.h
incrgram.h : incrgram.cpp

incrgram.cpp : incrgram.ypp
	$(BISON) -dv -o incrgram.tab.c incrgram.ypp
	$(SED) "s/yy/incr_yy/g" < incrgram.tab.c > incrgram.cpp
	$(SED) "s/yy/incr_yy/g" < incrgram.tab.h > incrgram.h
	rm incrgram.tab.c incrgram.tab.h
	
parser: incrgram.cpp incrscan.cpp

clean:
	$(RM) *.o core incrscan.cpp incrgram.cpp incrgram.h

distclean: clean
	$(RM) *.a lib*.so.*
