all : dynagraph gengraph 
#graphsearch/graphsearch

ROOT=.
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

SUBDIRS = common dynadag incrface fdp voronoi shortspline 
#graphsearch

INCS = -I. \
	-I.. -I../cdt \
	-I$(GRAPHVIZ_INC)

DEFINES = 

BASELIBS = -Lcommon -ldynagraph \
       -L$(GRAPHVIZ_LIB) -lagraph -lpathplan -lcdt

GLIBS = -Lcommon -ldynagraph \
       -L$(GRAPHVIZ_LIB) -lcdt -lagraph

OTHERLIBS = -Lincrface -lincrface \
	-Lfdp -lfdp \
    -Ldynadag -ldynadag \
	-Lshortspline -lshortspline \
	-Lvoronoi -lvoronoi

MANS = 

dynagraph : main.o libdynagraph.a libdynadag.a libincrface.a libfdp.a libvoronoi.a libshortspline.a
	$(CPPSLD) $(LDFLAGS) main.o $(OTHERLIBS) $(BASELIBS) -o dynagraph

gengraph : gengraph.o libdynagraph.a
	$(CPPSLD) $(LDFLAGS) gengraph.o $(GLIBS) -o gengraph

graphsearch/graphsearch :
	(cd graphsearch; make)

libdynagraph.a :
	(cd common; make)

libdynadag.a :
	(cd dynadag; make)

libincrface.a :
	(cd incrface; make)

libfdp.a :
	(cd fdp; make)

libvoronoi.a :
	(cd voronoi; make)

libshortspline.a :
	(cd shortspline; make)

install: dynagraph gengraph
	(for i in ${SUBDIRS}; do (cd $$i; make install); done)       
	$(MKPATH) $(BINDIR)
	$(INSTALL) dynagraph $(BINDIR)
#	$(MKPATH) $(MANDIR)
#	$(INSTALL) $(MANS) $(MANDIR)

distclean clean:
	(for i in ${SUBDIRS}; do (cd $$i; make $@); done)       
	$(RM) *.o core dynagraph gengraph
