all : dynagraph gengraph
#graphsearch/graphsearch

ROOT=.
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

SUBDIRS = common dynadag incrface pathplot shortspline graphsearch fdp shortspline voronoi

INCS = -I. \
	-I.. -I../cdt \
	-I$(GRAPHVIZ_INC)

DEFINES = -DHAVE_CONFIG_H

GVIZLIBS = -L$(GRAPHVIZ_LIB) \
       -lagraph -lpathplan -lcdt

DGLIBS = -Lincrface -lincrface \
	-Ldynadag -ldynadag \
	-Lpathplot -lpathplot \
	-Lfdp -lfdp \
	-Lshortspline -lshortspline \
	-Lvoronoi -lvoronoi \
    -Lcommon -ldynagraph

GGLIBS = -Lcommon -ldynagraph \
       -L$(GRAPHVIZ_LIB) \
       -lcdt -lagraph

OBJS = main.o IncrCalledBack.o DuplicateStream.o createConfiguration.o

MANS = 

GET_VERSION = `./dynagraph --v3rs10n`

dynagraph-whole : $(OBJS) common/libdynagraph.a dynadag/libdynadag.a incrface/libincrface.a pathplot/libpathplot.a fdp/libfdp.a voronoi/libvoronoi.a shortspline/libshortspline.a
	$(CPPSLD) $(LDFLAGS) $(OBJS) $(DGLIBS) $(GVIZLIBS) $(THREADLIBS) -o dynagraph-whole

dynagraph: dynagraph-whole
	strip dynagraph-whole -o dynagraph

release: dynagraph
	bzip2 -kc dynagraph > dynagraph-$(ARCH)-$(GET_VERSION).bz2

#*.o: *.h common/*.h incrface/*.h fdp/*.h dynadag/*.h voronoi/*.h shortspline/*.h pathplot/*.h

gengraph : gengraph.o common/libdynagraph.a
	$(CPPSLD) $(LDFLAGS) gengraph.o $(GGLIBS) $(THREADLIBS) -o gengraph

graphsearch/graphsearch :
	(cd graphsearch; $(MAKE))

common/libdynagraph.a :
	(cd common; $(MAKE))

dynadag/libdynadag.a :
	(cd dynadag; $(MAKE))

incrface/libincrface.a :
	(cd incrface; $(MAKE))

pathplot/libpathplot.a :
	(cd pathplot; $(MAKE))

fdp/libfdp.a :
	(cd fdp; $(MAKE))

voronoi/libvoronoi.a :
	(cd voronoi; $(MAKE))

shortspline/libshortspline.a :
	(cd shortspline; $(MAKE))

install: dynagraph gengraph
	(for i in ${SUBDIRS}; do (cd $$i; $(MAKE) install); done)       
	$(MKPATH) $(BINDIR)
	$(INSTALL) dynagraph $(BINDIR)

test: 
	(cd tests; $(MAKE) run)

distclean clean:
	(for i in ${SUBDIRS}; do (cd $$i; $(MAKE) $@); done)     
	(cd tests; $(MAKE) clean)  
	$(RM) *.o core dynagraph gengraph

-include $(OBJS:%.o=$(DEPDIR)/%.P)
