all : dynagraph gengraph
#graphsearch/graphsearch

ROOT=.
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

SUBDIRS = common dynadag incrface pathplot shortspline graphsearch fdp shortspline voronoi

INCS = -I. \
	-I.. -I../cdt \
	-I$(GRAPHVIZ_INC)

DEFINES = -DHAVE_CONFIG_H

BASELIBS = -Lcommon -ldynagraph \
       -L$(GRAPHVIZ_LIB) \
       -lagraph -lpathplan -lcdt

GLIBS = -Lcommon -ldynagraph \
       -L/usr/local/graphviz/lib \
       -lcdt -lagraph

OTHERLIBS = -Lincrface -lincrface \
	-Ldynadag -ldynadag \
	-Lpathplot -lpathplot \
	-Lfdp -lfdp \
	-Lshortspline -lshortspline \
	-Lvoronoi -lvoronoi

GGLIBS = -Lcommon -ldynagraph \
       -L$(GRAPHVIZ_LIB) \
       -lcdt -lagraph

OBJS = main.o IncrCalledBack.o DuplicateStream.o createConfiguration.o

MANS = 

GET_VERSION = `./dynagraph --v3rs10n`

dynagraph-whole : $(OBJS) libdynagraph.a libdynadag.a libincrface.a libpathplot.a libfdp.a libvoronoi.a libshortspline.a
	$(CPPSLD) $(LDFLAGS) $(OBJS) $(OTHERLIBS) $(BASELIBS) $(THREADLIBS) -o dynagraph-whole

dynagraph: dynagraph-whole
	strip dynagraph-whole -o dynagraph

release: dynagraph
	bzip2 -kc dynagraph > dynagraph-$(ARCH)-$(GET_VERSION).bz2

#*.o: *.h common/*.h incrface/*.h fdp/*.h dynadag/*.h voronoi/*.h shortspline/*.h pathplot/*.h

gengraph : gengraph.o libdynagraph.a
	$(CPPSLD) $(LDFLAGS) gengraph.o $(GLIBS) $(THREADLIBS) -o gengraph

graphsearch/graphsearch :
	(cd graphsearch; $(MAKE))

libdynagraph.a :
	(cd common; $(MAKE))

libdynadag.a :
	(cd dynadag; $(MAKE))

libincrface.a :
	(cd incrface; $(MAKE))

libpathplot.a :
	(cd pathplot; $(MAKE))

libfdp.a :
	(cd fdp; $(MAKE))

libvoronoi.a :
	(cd voronoi; $(MAKE))

libshortspline.a :
	(cd shortspline; $(MAKE))

install: dynagraph gengraph
	(for i in ${SUBDIRS}; do (cd $$i; $(MAKE) install); done)       
	$(MKPATH) $(BINDIR)
	$(INSTALL) dynagraph $(BINDIR)

test: 
	(cd tests; $(MAKE) run)

distclean clean:
	(for i in ${SUBDIRS}; do (cd $$i; $(MAKE) $@); done)     
	(cd tests; $(MAKE) clean)  
	$(RM) *.o core dynagraph gengraph

-include $(OBJS:%.o=$(DEPDIR)/%.P)
