all: libshortspline.a

include ../../Config.mk
include ../../makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I../../pathplan \
	-I../../cdt

DEFINES = -DHAVE_CONFIG_H

OBJS = ObAvSplinerEngine.o legal_arrangement.o

HFILES = ObAvSplinerEngine.h ObstacleAvoiderSpliner.h legal_arrangement.h simple.h

libshortspline.a : $(OBJS)
	$(AR) cr libshortspline.a $(OBJS)
	$(RANLIB) libshortspline.a

$(OBJS) : $(HFILES)

install: libshortspline.a
#	$(MKPATH) $(LIBDIR)
#	$(INSTALL) libshortspline.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
