#!/bin/sh
exts=
opts="-x $4"
for i in $5 $6 $7 $8 $9
do 
	if test $i = dotco
	then opts="$opts -d"
	elif test $i = rotat
	then opts="$opts -a rankdir=LR"
	elif test $i = imed
	then opts="$opts -a intermediate=true"
	elif test $i = eflow
	then opts="$opts -a emphasizeflow=true"
	else echo dotest: option $i unknown; exit 9
	fi
	exts=$exts.$i
done
opts="$opts -rv9 -o9 $3/$2$exts.svg"
echo "$1 $opts < $2.incr > $3/$2$exts.incrout"
$1 $opts < $2.incr > $3/$2$exts.incrout
