.SUFFIXES  : .incr .incrout

DYNAGRAPH=../dynagraph
DY_OPTS=-x

SUF_ROTAT=rotat
AT_ROTAT=-a rankdir=LR
SUF_INTER=imed
AT_INTER=-a intermediate=true
SUF_EFLOW=eflow
AT_EFLOW=-a emphasizeflow=true
SUF_DOTCO=dotco
OPT_DOTCO=-d

OUTDIR=results

run: *.incr showem

showem:
	@echo Searching output for exceptions...
	@if grep exception $(OUTDIR)/*.incrout; then echo "Tasty bugs."; else echo "Everything seems fine."; fi
	
$(OUTDIR):
	mkdir -p $(OUTDIR)

*.incr: always $(OUTDIR)
	-./dotest $(DYNAGRAPH) $* $(OUTDIR)
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) rotat
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) imed
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) eflow
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) rotat imed
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) rotat eflow 
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) imed eflow
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) rotat imed eflow
	-./dotest $(DYNAGRAPH) $* $(OUTDIR)
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) rotat
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) imed
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) eflow
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) rotat imed
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) rotat eflow 
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) imed eflow
	-./dotest $(DYNAGRAPH) $* $(OUTDIR) rotat imed eflow

always: 

clean:
	rm -f results/*.incrout results/*.svg
