all: graphsearch

ROOT=..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I$(GRAPHVIZ_INC) \
	-I$(BOOST_INC)
	
LIBS = -L../common -ldynagraph \
	-L$(GRAPHVIZ_LIB) -lagraph -lcdt

DEFINES = 

OBJS = gsscan.o gsgram.o graphsearch.o gscmds.o Pattern.o Search.o

HFILES = Pattern.h Search.h gscmds.h gsxep.h gsgram.h

graphsearch: $(OBJS)
	$(CPPSLD) -o graphsearch $(OBJS) $(LIBS)

$(OBJS) : $(HFILES)

gsscan.cpp: gsscan.lpp
	$(FLEX) gsscan.lpp
	$(SED) "s/yy/gs_yy/g" < lex.yy.c > gsscan.cpp
	rm lex.yy.c

gsgram.h : gsgram.cpp

gsgram.cpp : gsgram.ypp
	$(BISON) -dv -o gsgram.tab.c gsgram.ypp
	$(SED) "s/yy/gs_yy/g" < gsgram.tab.c > gsgram.cpp
	$(SED) "s/yy/gs_yy/g" < gsgram.tab.h > gsgram.h
	rm gsgram.tab.c gsgram.tab.h

install: graphsearch
#	$(MKPATH) $(BINDIR)
#	$(INSTALL) graphsearch $(BINDIR)

clean:
	$(RM) *.o core gsgram.h gsgram.cpp gsscan.cpp

distclean: clean
	$(RM) *.a lib*.so.* graphsearch gsgram.cpp gsgram.h gsscan.cpp
