all: libvoronoi.a

ROOT=..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I$(GRAPHVIZ_INC)

DEFINES = 

OBJS = edges.o heap.o hedges.o info.o process.o site.o voronoi.o

HFILES = edges.h hedges.h info.h site.h voronoi.h 

libvoronoi.a : $(OBJS)
	$(AR) cr libvoronoi.a $(OBJS)
	$(RANLIB) libvoronoi.a

$(OBJS) : $(HFILES)

install: libvoronoi.a
#	$(MKPATH) $(LIBDIR)
#	$(INSTALL) libvoronoi.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
