all: libfdp.a

ROOT=..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I/usr/local/graphviz/include

DEFINES = -DHAVE_CONFIG_H

OBJS = createFDPEngine.o grid.o layout.o process.o

HFILES = fdp.h grid.h macros.h ../common/*.h 

libfdp.a : $(OBJS)
	$(AR) cr libfdp.a $(OBJS)
	$(RANLIB) libfdp.a

$(OBJS) : $(HFILES)

install: libfdp.a
#	$(MKPATH) $(LIBDIR)
#	$(INSTALL) libfdp.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
