all: libfdp.a

ROOT=..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I$(GRAPHVIZ_INC)

DEFINES = 

OBJS = grid.o layout.o process.o

HFILES = FVSCombo.h fdp.h grid.h macros.h

libfdp.a : $(OBJS)
	$(AR) cr libfdp.a $(OBJS)
	$(RANLIB) libfdp.a

$(OBJS) : $(HFILES)

install: libfdp.a
#	$(MKPATH) $(LIBDIR)
#	$(INSTALL) libfdp.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
