all: libdynadag.a

ROOT=..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I/usr/local/graphviz/include 

DEFINES = -DHAVE_CONFIG_H

OBJS = createDynaDAGEngine.o Check.o Config.o ConstraintGraph.o \
    DotlikeOptimizer.o DynaDAG.o \
    FlexiSpline.o getCrossoptModelNodes.o Measurements.o Medians.o \
    SetYs.o SiftMatrix.o Spline.o Update.o UVCross.o XSolver.o

HFILES = Config.h	ConseqRanks.h		ConstraintGraph.h \
    Constraints.h	Crossings.h		DotlikeOptimizer.h \
    DynaDAG.h		DynaDAGChains.h		DynaDAGDefs.h \
    DynaDAGLayout.h	DynaDAGModel.h		DynaDAGServices.h \
    FlexiRanks.h	FlexiSpliner.h		Measurements.h \
    Medians.h		NSRanker.h		NSRankerAttrs.h \
    Optimizer.h		Rank.h			SiftMatrix.h \
    Spliner.h		XSolver.h		ns.h \
    nsdat.h \
    ../common/*.h ../pathplot/*.h ../shortspline/*.h

libdynadag.a : $(OBJS)
	$(AR) cr libdynadag.a $(OBJS)
	$(RANLIB) libdynadag.a

$(OBJS) : $(HFILES)

install: libdynadag.a
#	$(MKPATH) $(LIBDIR)
#	$(INSTALL) libdynadag.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
