all: libdynadag.a

ROOT=..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I.. -I../.. \
	-I$(GRAPHVIZ_INC)

DEFINES = 

OBJS = Check.o Config.o ConstraintGraph.o DotlikeOptimizer.o DynaDAG.o \
    FlexiSpline.o getCrossoptModelNodes.o Measurements.o Medians.o Ranker.o \
    SetYs.o SiftMatrix.o Spline.o Update.o UVCross.o XSolver.o

HFILES = DynaDAG.h Measurements.h Medians.h SiftMatrix.h ns.h nsdat.h

libdynadag.a : $(OBJS)
	$(AR) cr libdynadag.a $(OBJS)
	$(RANLIB) libdynadag.a

$(OBJS) : $(HFILES)

install: libdynadag.a
#	$(MKPATH) $(LIBDIR)
#	$(INSTALL) libdynadag.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
