all: libdynadag.a

ROOT=..
include $(ROOT)/Config.mk
include $(ROOT)/makearch/$(ARCH)

INCS =	-I.. -I../.. \
	$(GRAPHVIZ_INCS) \
	-I$(BOOST_INC)

DEFINES = -DHAVE_CONFIG_H

OBJS = Check.o Config.o ConstraintGraph.o \
    DotlikeOptimizer.o DynaDAG.o EdgeDrawing.o \
    FlexiSpline.o getCrossoptModelNodes.o Measurements.o Medians.o \
    SetYs.o SiftMatrix.o Spline.o Update.o UVCross.o XSolver.o
-include $(OBJS:%.o=$(DEPDIR)/%.P)

libdynadag.a : $(OBJS)
	$(AR) cr libdynadag.a $(OBJS)
	$(RANLIB) libdynadag.a

install: libdynadag.a
#	$(MKPATH) $(LIBDIR)
#	$(INSTALL) libdynadag.a $(LIBDIR)

clean:
	$(RM) *.o core

distclean: clean
	$(RM) *.a lib*.so.*
